application:
  host: 127.0.0.1
  port: 3000
  secret: "my-long-secret-shhhhh"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "<my_xml_token>"
